In [1]:
import os
import pandas as pd

In [17]:
DATA_DIR = "../data/raw/aclImdb"

print(os.listdir(DATA_DIR))

TRAIN_DIR = os.path.join(DATA_DIR, "train")
TEST_DIR = os.path.join(DATA_DIR, "test")

print("Contents of dataset folder:")
print(os.listdir(DATA_DIR))

print("\nContents of train folder:")
print(os.listdir(TRAIN_DIR))

print("\nContents of test folder:")
print(os.listdir(TEST_DIR))

OUTPUT_DIR = "../data/processed"

['imdb.vocab', 'imdbEr.txt', 'README', 'test', 'train']
Contents of dataset folder:
['imdb.vocab', 'imdbEr.txt', 'README', 'test', 'train']

Contents of train folder:
['labeledBow.feat', 'neg', 'pos', 'unsup', 'unsupBow.feat', 'urls_neg.txt', 'urls_pos.txt', 'urls_unsup.txt']

Contents of test folder:
['labeledBow.feat', 'neg', 'pos', 'urls_neg.txt', 'urls_pos.txt']

In [5]:
def load_reviews(folder_path, label):
    """
    Reads all .txt review files from a folder.

    Parameters:
        folder_path : path to the folder containing reviews
        label       : sentiment label
                      0 = negative
                      1 = positive

    Returns:
        A list of dictionaries containing review text and label.
    """
    
    reviews = []

    for filename in os.listdir(folder_path):

        if filename.endswith(".txt"):

            file_path = os.path.join(folder_path, filename)

            with open(file_path, "r", encoding="utf-8") as file:
                text = file.read()

            reviews.append({
                "text": text,
                "label": label
            })

    return reviews

In [ ]:
train_pos = load_reviews(
    os.path.join(TRAIN_DIR, "pos"),
    1
)

train_neg = load_reviews(
    os.path.join(TRAIN_DIR, "neg"),
    0
)

print("Positive training reviews:", len(train_pos))
print("Negative training reviews:", len(train_neg))

Positive training reviews: 12500
Negative training reviews: 12500

In [8]:
train_data = train_pos + train_neg

print("Total training reviews:", len(train_data))

Total training reviews: 25000

In [9]:
train_df = pd.DataFrame(train_data)

print("Training DataFrame shape:", train_df.shape)
train_df.head()

Training DataFrame shape: (25000, 2)

                                                text  label
0  Bromwell High is a cartoon comedy. It ran at t...      1
1  Homelessness (or Houselessness as George Carli...      1
2  Brilliant over-acting by Lesley Ann Warren. Be...      1
3  This is easily the most underrated film inn th...      1
4  This is not the typical Mel Brooks film. It wa...      1

In [10]:
print(train_df["label"].value_counts())
print("Negative reviews:", (train_df["label"] == 0).sum())
print("Positive reviews:", (train_df["label"] == 1).sum())

label
1    12500
0    12500
Name: count, dtype: int64
Negative reviews: 12500
Positive reviews: 12500

In [11]:
test_pos = load_reviews(
    os.path.join(TEST_DIR, "pos"),
    1
)

test_neg = load_reviews(
    os.path.join(TEST_DIR, "neg"),
    0
)

print("Positive test reviews:", len(test_pos))
print("Negative test reviews:", len(test_neg))

Positive test reviews: 12500
Negative test reviews: 12500

In [12]:
test_data = test_pos + test_neg

test_df = pd.DataFrame(test_data)

print("Test DataFrame shape:", test_df.shape)

print(test_df["label"].value_counts())

test_df.head()

Test DataFrame shape: (25000, 2)
label
1    12500
0    12500
Name: count, dtype: int64

                                                text  label
0  I went and saw this movie last night after bei...      1
1  Actor turned director Bill Paxton follows up h...      1
2  As a recreational golfer with some knowledge o...      1
3  I saw this film in a sneak preview, and it is ...      1
4  Bill Paxton has taken the true story of the 19...      1

In [13]:
train_df = train_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

test_df = test_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [14]:
train_df.head()

                                                text  label
0  In Panic In The Streets Richard Widmark plays ...      1
1  If you ask me the first one was really better ...      0
2  I am a big fan a Faerie Tale Theatre and I've ...      1
3  I just finished reading a book about Dillinger...      0
4  Greg Davis and Bryan Daly take some crazed sta...      0

In [18]:
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Output folder ready! ✅")

Output folder ready! ✅

In [19]:
train_path = os.path.join(
    OUTPUT_DIR,
    "imdb_train.csv"
)

train_df.to_csv(
    train_path,
    index=False,
    encoding="utf-8"
)

print("Training CSV saved successfully! ✅")
print("Location:", train_path)

Training CSV saved successfully! ✅
Location: ../data/processed\imdb_train.csv

In [20]:
test_path = os.path.join(
    OUTPUT_DIR,
    "imdb_test.csv"
)

test_df.to_csv(
    test_path,
    index=False,
    encoding="utf-8"
)

print("Testing CSV saved successfully! ✅")
print("Location:", test_path)

Testing CSV saved successfully! ✅
Location: ../data/processed\imdb_test.csv

In [23]:
train_check = pd.read_csv(
    train_path,
    encoding="utf-8"
)

test_check = pd.read_csv(
    test_path,
    encoding="utf-8"
)

print("Training CSV shape:", train_check.shape)
print("Testing CSV shape:", test_check.shape)

print("\nTraining columns:")
print(train_check.columns)

print("\nTesting columns:")
print(test_check.columns)

Training CSV shape: (25000, 2)
Testing CSV shape: (25000, 2)

Training columns:
Index(['text', 'label'], dtype='object')

Testing columns:
Index(['text', 'label'], dtype='object')

In [24]:
train_check.head()

                                                text  label
0  In Panic In The Streets Richard Widmark plays ...      1
1  If you ask me the first one was really better ...      0
2  I am a big fan a Faerie Tale Theatre and I've ...      1
3  I just finished reading a book about Dillinger...      0
4  Greg Davis and Bryan Daly take some crazed sta...      0

In [25]:
test_check.head()

                                                text  label
0  When I was a kid, I loved "Tiny Toons". I espe...      1
1  The setup for "Nature of the Beast" is ingenio...      0
2  I do not have much to say than this is a great...      1
3  Extremely formulaic with cosmic-sized logic ho...      0
4  I actually liked certain things about this gam...      0

In [26]:
print("Missing values in training data:")
print(train_df.isnull().sum())

print("\nMissing values in testing data:")
print(test_df.isnull().sum())

Missing values in training data:
text     0
label    0
dtype: int64

Missing values in testing data:
text     0
label    0
dtype: int64

In [27]:
print("=" * 50)
print("IMDB DATASET CONVERSION COMPLETE")
print("=" * 50)

print(f"Training reviews : {len(train_df):,}")
print(f"Testing reviews  : {len(test_df):,}")

print("\nTraining class distribution:")
print(train_df["label"].value_counts().sort_index())

print("\nTesting class distribution:")
print(test_df["label"].value_counts().sort_index())

print("\nCSV files:")
print(train_path)
print(test_path)

==================================================
IMDB DATASET CONVERSION COMPLETE
==================================================
Training reviews : 25,000
Testing reviews  : 25,000

Training class distribution:
label
0    12500
1    12500
Name: count, dtype: int64

Testing class distribution:
label
0    12500
1    12500
Name: count, dtype: int64

CSV files:
../data/processed\imdb_train.csv
../data/processed\imdb_test.csv